add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold yellow"
symbol = " "

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[username]
style_user = "bold green"
show_always = false

[cmd_duration]
min_time = 10_000 
format = " took [$duration]($style)"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false
