# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold yellow"
symbol = " "

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = true

[username]
style_user = "bold green"
show_always = false
