so ~/.vim/src/keymaps.vim
so ~/.vim/src/plugins.vim
syntax enable

set smarttab
set nohlsearch
set ignorecase
set incsearch
set encoding=utf-8
set ruler
set showcmd
set wildmenu
set cursorline
set number
set relativenumber
set numberwidth=1
set noerrorbells
set mouse=a
set title
set background=dark
set clipboard="unnamedplus"
set autoread
set sw=2
set noswapfile
set scrolloff=8
set textwidth=300
set splitright
set splitbelow

if has('termguicolors')
	set termguicolors
endif

colorscheme darcula
let g:airline_theme='base16'
